version: '3.7'
networks:
  default:
    external:
      name: odoo-net

services:
  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}:${WEB_IMAGE_TAG}
    build: ./
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - odoo-web-data16:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons-clase:/mnt/addons-clase
    #entrypoint: "odoo -c /etc/odoo/odoo.conf --dev all -d clase"
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data16:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4:6.17
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    volumes:
      - odoo-pgadmin-data16:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
volumes:
  odoo-db-data16:
  odoo-web-data16:
  odoo-pgadmin-data16: